import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'bn', 'ta', 'te', 'or', 'ml', 'hi', 'ur'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? bnText = '',
    String? taText = '',
    String? teText = '',
    String? orText = '',
    String? mlText = '',
    String? hiText = '',
    String? urText = '',
  }) =>
      [
        enText,
        bnText,
        taText,
        teText,
        orText,
        mlText,
        hiText,
        urText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // auth_Login
  {
    '3p97u62u': {
      'en': 'Welcome Back!',
      'bn': 'ফিরে আসার জন্য স্বাগতম!',
      'hi': 'वापसी पर स्वागत है!',
      'ml': 'തിരികെ സ്വാഗതം!',
      'or': 'ପୁଣି ଥରେ ସ୍ୱାଗତ!',
      'ta': 'மீண்டும் வருக!',
      'te': 'పునఃస్వాగతం!',
      'ur': 'خوش آمدید!',
    },
    'xkz4xjo6': {
      'en': 'Use the form below to access your account.',
      'bn': 'আপনার অ্যাকাউন্ট অ্যাক্সেস করতে নীচের ফর্ম ব্যবহার করুন.',
      'hi': 'अपने खाते तक पहुंचने के लिए नीचे दिए गए फॉर्म का उपयोग करें।',
      'ml': 'നിങ്ങളുടെ അക്കൗണ്ട് ആക്‌സസ് ചെയ്യാൻ ചുവടെയുള്ള ഫോം ഉപയോഗിക്കുക.',
      'or': 'ଆପଣଙ୍କ ଖାତାକୁ ପ୍ରବେଶ କରିବାକୁ ନିମ୍ନରେ ଥିବା ଫର୍ମ ବ୍ୟବହାର କରନ୍ତୁ |',
      'ta': 'உங்கள் கணக்கை அணுக கீழே உள்ள படிவத்தைப் பயன்படுத்தவும்.',
      'te': 'మీ ఖాతాను యాక్సెస్ చేయడానికి దిగువ ఫారమ్‌ని ఉపయోగించండి.',
      'ur': 'اپنے اکاؤنٹ تک رسائی کے لیے نیچے دیے گئے فارم کا استعمال کریں۔',
    },
    'k9u5spqi': {
      'en': '',
      'bn': 'ইমেইল ঠিকানা',
      'hi': 'मेल पता',
      'ml': 'ഇമെയിൽ വിലാസം',
      'or': 'ଈମୈଲ ଠିକଣା',
      'ta': 'மின்னஞ்சல் முகவரி',
      'te': 'ఇమెయిల్ చిరునామా',
      'ur': 'ای میل اڈریس',
    },
    'f4xxyrqv': {
      'en': 'Enter your email here...',
      'bn': 'এখানে আপনার ইমেল ঠিকানা লিখুন...',
      'hi': 'अपना ई मेल यहा भरे...',
      'ml': 'നിങ്ങളുടെ ഇമെയിൽ ഇവിടെ നൽകുക...',
      'or': 'ଏଠାରେ ଆପଣଙ୍କର ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ ...',
      'ta': 'உங்கள் மின்னஞ்சலை இங்கே உள்ளிடவும்...',
      'te': 'మీ ఇమెయిల్‌ను ఇక్కడ నమోదు చేయండి...',
      'ur': 'اپنا ای میل یہاں درج کریں...',
    },
    'lfzvgi5q': {
      'en': '',
      'bn': 'পাসওয়ার্ড',
      'hi': 'पासवर्ड',
      'ml': 'Password',
      'or': 'ପାସୱାର୍ଡ',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్వర్డ్',
      'ur': 'پاس ورڈ',
    },
    'wt8sx5du': {
      'en': 'Enter your password here...',
      'bn': 'এখানে আপনার পাসওয়ার্ড লিখুন...',
      'hi': 'यहां अपना पासवर्ड डालें...',
      'ml': 'നിങ്ങളുടെ പാസ്‌വേഡ് ഇവിടെ നൽകുക...',
      'or': 'ଏଠାରେ ଆପଣଙ୍କର ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ ...',
      'ta': 'உங்கள் கடவுச்சொல்லை இங்கே உள்ளிடவும்...',
      'te': 'మీ పాస్‌వర్డ్‌ను ఇక్కడ నమోదు చేయండి...',
      'ur': 'یہاں اپنا پاس ورڈ درج کریں...',
    },
    'bio9hjsl': {
      'en': 'Forgot Password?',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    's8bicxzh': {
      'en': 'Forgot Password?',
      'bn': 'পাসওয়ার্ড ভুলে গেছেন?',
      'hi': 'पासवर्ड भूल गए?',
      'ml': 'പാസ്വേഡ് മറന്നോ?',
      'or': 'ପାସୱାର୍ଡ଼ ଭୁଲି ଗଲେ କି?',
      'ta': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'te': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'ur': 'پاسورڈ بھول گے؟',
    },
    'm9klj9ah': {
      'en': 'Login',
      'bn': 'প্রবেশ করুন',
      'hi': 'लॉग इन करें',
      'ml': 'ലോഗിൻ',
      'or': 'ଭିତରକୁ ଯାଉ',
      'ta': 'உள்நுழைய',
      'te': 'ప్రవేశించండి',
      'ur': 'لاگ ان کریں',
    },
    'kfm1khsu': {
      'en': 'Field is required',
      'bn': 'আপনি উত্তর দিবেন না',
      'hi': 'ये स्थान भरा जाना है',
      'ml': 'ഫീൽഡ് ആവശ്യമാണ്',
      'or': 'କ୍ଷେତ୍ର ଆବଶ୍ୟକ |',
      'ta': 'இந்த பகுதி அவசியமானது',
      'te': 'ఫీల్డ్ అవసరం',
      'ur': 'فیلڈ کی ضرورت ہے',
    },
    'p7rdh4r8': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প চয়ন করুন',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'ml': 'ഡ്രോപ്പ്ഡൗണിൽ നിന്ന് ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
      'or': 'ଦୟାକରି ଡ୍ରପଡାଉନରୁ ଏକ ବିକଳ୍ପ ବାଛନ୍ତୁ |',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి',
      'ur': 'براہ کرم ڈراپ ڈاؤن سے ایک آپشن منتخب کریں۔',
    },
    'ud7wd8di': {
      'en': 'Field is required',
      'bn': 'আপনি উত্তর দিবেন না',
      'hi': 'ये स्थान भरा जाना है',
      'ml': 'ഫീൽഡ് ആവശ്യമാണ്',
      'or': 'କ୍ଷେତ୍ର ଆବଶ୍ୟକ |',
      'ta': 'இந்த பகுதி அவசியமானது',
      'te': 'ఫీల్డ్ అవసరం',
      'ur': 'فیلڈ کی ضرورت ہے',
    },
    'bwbzfuju': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প চয়ন করুন',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'ml': 'ഡ്രോപ്പ്ഡൗണിൽ നിന്ന് ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
      'or': 'ଦୟାକରି ଡ୍ରପଡାଉନରୁ ଏକ ବିକଳ୍ପ ବାଛନ୍ତୁ |',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి',
      'ur': 'براہ کرم ڈراپ ڈاؤن سے ایک آپشن منتخب کریں۔',
    },
    'iha5socs': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'ml': 'വീട്',
      'or': 'ଘର',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'ur': 'گھر',
    },
  },
  // forgotPassword
  {
    '3hcuc8v6': {
      'en': 'Forgot Password',
      'bn': 'পাসওয়ার্ড ভুলে গেছেন',
      'hi': 'पासवर्ड भूल गए',
      'ml': 'പാസ്വേഡ് മറന്നോ',
      'or': 'ପାସୱାର୍ଡ଼ ଭୁଲି ଗଲେ କି',
      'ta': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
      'te': 'పాస్‌వర్డ్ మర్చిపోయాను',
      'ur': 'پاسورڈ بھول گے',
    },
    'sjjd1jb9': {
      'en':
          'Don\'t remember your password? Enter the email associated with your account below and we will send you a new link.',
      'bn':
          'আপনার পাসওয়ার্ড মনে নেই? নীচে আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেলটি লিখুন এবং আমরা আপনাকে একটি নতুন লিঙ্ক পাঠাব৷',
      'hi':
          'क्या आपको अपना पासवर्ड याद नहीं है? नीचे अपने खाते से संबद्ध ईमेल दर्ज करें और हम आपको एक नया लिंक भेजेंगे।',
      'ml':
          'നിങ്ങളുടെ പാസ്‌വേഡ് ഓർമ്മയില്ലേ? നിങ്ങളുടെ അക്കൗണ്ടുമായി ബന്ധപ്പെട്ട ഇമെയിൽ ചുവടെ നൽകുക, ഞങ്ങൾ നിങ്ങൾക്ക് ഒരു പുതിയ ലിങ്ക് അയയ്ക്കും.',
      'or':
          'ଆପଣଙ୍କର ପାସୱାର୍ଡ ମନେ ନାହିଁ? ନିମ୍ନରେ ଆପଣଙ୍କର ଖାତା ସହିତ ଜଡିତ ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ ଏବଂ ଆମେ ଆପଣଙ୍କୁ ଏକ ନୂତନ ଲିଙ୍କ୍ ପଠାଇବୁ |',
      'ta':
          'உங்கள் கடவுச்சொல் நினைவில் இல்லையா? உங்கள் கணக்குடன் தொடர்புடைய மின்னஞ்சலை கீழே உள்ளிடவும், நாங்கள் உங்களுக்கு ஒரு புதிய இணைப்பை அனுப்புவோம்.',
      'te':
          'మీ పాస్‌వర్డ్ గుర్తులేదా? దిగువన మీ ఖాతాతో అనుబంధించబడిన ఇమెయిల్‌ను నమోదు చేయండి మరియు మేము మీకు కొత్త లింక్‌ను పంపుతాము.',
      'ur':
          'اپنا پاس ورڈ یاد نہیں ہے؟ ذیل میں اپنے اکاؤنٹ سے وابستہ ای میل درج کریں اور ہم آپ کو ایک نیا لنک بھیجیں گے۔',
    },
    'tzm5opaa': {
      'en': 'Email Address',
      'bn': 'ইমেইল ঠিকানা',
      'hi': 'मेल पता',
      'ml': 'ഇമെയിൽ വിലാസം',
      'or': 'ଈମୈଲ ଠିକଣା',
      'ta': 'மின்னஞ்சல் முகவரி',
      'te': 'ఇమెయిల్ చిరునామా',
      'ur': 'ای میل اڈریس',
    },
    'uvsotzng': {
      'en': 'Please enter a valid email...',
      'bn': 'একটি বৈধ ইমেইল প্রবেশ করুন...',
      'hi': 'कृपया एक मान्य ईमेल दर्ज करें...',
      'ml': 'സാധുവായ ഒരു ഇമെയിൽ നൽകുക...',
      'or': 'ଦୟାକରି ଏକ ବ valid ଧ ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ ...',
      'ta': 'சரியான மின்னஞ்சலை உள்ளிடவும்...',
      'te': 'దయచేసి సరైన ఈమెయిల్ ఇవ్వండి...',
      'ur': 'ایک درست ای میل درج کریں...',
    },
    '3sdzjivm': {
      'en': 'Send Reset Link',
      'bn': 'রিসেট লিঙ্ক পাঠান',
      'hi': 'रीसेट लिंक भेजें',
      'ml': 'റീസെറ്റ് ലിങ്ക് അയയ്ക്കുക',
      'or': 'ପୁନ Res ସେଟ୍ ଲିଙ୍କ୍ ପଠାନ୍ତୁ |',
      'ta': 'மீட்டமை இணைப்பை அனுப்பவும்',
      'te': 'రీసెట్ లింక్‌ని పంపండి',
      'ur': 'ری سیٹ لنک بھیجیں۔',
    },
    '8p6xd6cl': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'ml': 'വീട്',
      'or': 'ଘର',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'ur': 'گھر',
    },
  },
  // Main_Home
  {
    'ieqg872u': {
      'en': 'Dashboard',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jdbbwbbl': {
      'en': 'TradeyPlus',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hks1ysfh': {
      'en': '\$ 120,000',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0ej0vdzm': {
      'en': '12%',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'muxmgdvm': {
      'en': ' Increase From the Target',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'khatwb9s': {
      'en': 'Private Stock',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ztpzcd6q': {
      'en': '\$12,000',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ara2w5ti': {
      'en': '12%',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5l23wfhv': {
      'en': ' Increase From the Target',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fi0tpvyl': {
      'en': 'Public Stock',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'sfrlfhdi': {
      'en': '\$12,000',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ikayuz1w': {
      'en': '12%',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yixda5yv': {
      'en': ' Increase From the Target',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ypnec5hn': {
      'en': 'Analytics Report',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'la5xl5tp': {
      'en': 'Monthly',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lqeydt53': {
      'en': 'Monthly',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fuen5f97': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9eqwh5la': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xbg0j6b1': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k8b9z5tb': {
      'en': 'Month',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x063edgc': {
      'en': 'Amount',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xdxbdj20': {
      'en': 'home',
      'bn': '__',
      'hi': '__',
      'ml': '__',
      'or': '__',
      'ta': '__',
      'te': '__',
      'ur': '__',
    },
  },
  // Main_customerList
  {
    'n99lg1qh': {
      'en': 'Customers',
      'bn': 'গ্রাহকদের',
      'hi': 'ग्राहकों',
      'ml': 'ഉപഭോക്താക്കൾ',
      'or': 'ଗ୍ରାହକ',
      'ta': 'வாடிக்கையாளர்கள்',
      'te': 'వినియోగదారులు',
      'ur': 'گاہکوں',
    },
    'x7g0vd0z': {
      'en': 'Total Investors',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '99tnqf20': {
      'en': ' this month',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xgzv1eny': {
      'en': 'Total members',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4uqqoz51': {
      'en': ' this month',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8blmisjx': {
      'en': 'Our Users',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hdy4xx49': {
      'en': 'Search Order',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zr9zfu53': {
      'en': 'Create Users',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ncfshgie': {
      'en': 'Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3uyt5hzr': {
      'en': 'Phone Number',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm20y3rfi': {
      'en': 'Nationality',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8k5leo4e': {
      'en': 'Balance',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ppqw2jdk': {
      'en': 'Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yo0rira3': {
      'en': 'Edit',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'voobws8t': {
      'en': 'Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0th1hkvj': {
      'en': 'Phone Number',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '82za59cf': {
      'en': 'Nationality',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u63u6y9h': {
      'en': 'Email',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u5w279jc': {
      'en': 'Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '18x6mxif': {
      'en': 'Edit',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5rrn7kk7': {
      'en': 'Create Users',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3ourv2w9': {
      'en': 'customerList',
      'bn': '__',
      'hi': '__',
      'ml': '__',
      'or': '__',
      'ta': '__',
      'te': '__',
      'ur': '__',
    },
  },
  // Main_profilePage
  {
    'qrxn5crt': {
      'en': 'My Profile',
      'bn': 'আমার প্রোফাইল',
      'hi': 'मेरी प्रोफाइल',
      'ml': 'എന്റെ പ്രൊഫൈൽ',
      'or': 'ମୋର ପ୍ରୋଫାଇଲ୍',
      'ta': 'என் சுயவிவரம்',
      'te': 'నా జీవన వివరణ',
      'ur': 'میری پروفائل',
    },
    'fyxsf6vn': {
      'en': 'Account Settings',
      'bn': 'অ্যাকাউন্ট সেটিংস',
      'hi': 'अकाउंट सेटिंग',
      'ml': 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
      'or': 'ଖାତା ସେଟିଂ',
      'ta': 'கணக்கு அமைப்புகள்',
      'te': 'ఖాతా సెట్టింగ్‌లు',
      'ur': 'اکاؤنٹ کی ترتیبات',
    },
    'h43llaan': {
      'en': 'Change Password',
      'bn': 'পাসওয়ার্ড পরিবর্তন করুন',
      'hi': 'पासवर्ड बदलें',
      'ml': 'പാസ്വേഡ് മാറ്റുക',
      'or': 'ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
      'ta': 'கடவுச்சொல்லை மாற்று',
      'te': 'పాస్‌వర్డ్ మార్చండి',
      'ur': 'پاس ورڈ تبدیل کریں',
    },
    'b1lw0hfu': {
      'en': 'Edit Profile',
      'bn': 'জীবন বৃত্তান্ত সম্পাদনা',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'ml': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'or': 'ପ୍ରୋଫାଇଲ୍ ଏଡ଼ିଟ୍ କରନ୍ତୁ',
      'ta': 'சுயவிவரத்தைத் திருத்து',
      'te': 'ప్రొఫైల్‌ని సవరించండి',
      'ur': 'پروفائل میں ترمیم کریں',
    },
    'lsgyi20x': {
      'en': 'Light Mode',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wljpbxal': {
      'en': 'Dark Mode',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'abqf147c': {
      'en': 'Log Out',
      'bn': 'প্রস্থান',
      'hi': 'लॉग आउट',
      'ml': 'ലോഗ് ഔട്ട് ചെയ്യുക',
      'or': 'ପ୍ରସ୍ଥାନ କର',
      'ta': 'வெளியேறு',
      'te': 'లాగ్ అవుట్ చేయండి',
      'ur': 'لاگ آوٹ',
    },
    'o3dp9tss': {
      'en': 'profile',
      'bn': '__',
      'hi': '__',
      'ml': '__',
      'or': '__',
      'ta': '__',
      'te': '__',
      'ur': '__',
    },
  },
  // userDetails
  {
    '9t913b44': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'ml': 'വീട്',
      'or': 'ଘର',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'ur': 'گھر',
    },
  },
  // editProfile
  {
    '20uycztj': {
      'en': 'Edit Profile',
      'bn': 'জীবন বৃত্তান্ত সম্পাদনা',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'ml': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'or': 'ପ୍ରୋଫାଇଲ୍ ଏଡ଼ିଟ୍ କରନ୍ତୁ',
      'ta': 'சுயவிவரத்தைத் திருத்து',
      'te': 'ప్రొఫైల్‌ని సవరించండి',
      'ur': 'پروفائل میں ترمیم کریں',
    },
  },
  // searchPage
  {
    'ao46xsuv': {
      'en': 'Add Members',
      'bn': 'সদস্য যোগ করুন',
      'hi': 'सदस्य जोड़ें',
      'ml': 'അംഗങ്ങളെ ചേർക്കുക',
      'or': 'ସଦସ୍ୟ ଯୋଡନ୍ତୁ |',
      'ta': 'உறுப்பினர்களைச் சேர்க்கவும்',
      'te': 'సభ్యులను జోడించండి',
      'ur': 'ممبرز کو شامل کریں۔',
    },
    'g8rv8zhr': {
      'en': 'Search members...',
      'bn': 'সদস্যদের খুঁজুন...',
      'hi': 'सदस्य खोजें...',
      'ml': 'അംഗങ്ങളെ തിരയുക...',
      'or': 'ସଦସ୍ୟମାନଙ୍କୁ ଖୋଜ ...',
      'ta': 'உறுப்பினர்களைத் தேடு...',
      'te': 'సభ్యులను వెతకండి...',
      'ur': 'اراکین کو تلاش کریں...',
    },
    'op7ngmsb': {
      'en': 'Option 1',
      'bn': 'বিকল্প 1',
      'hi': 'विकल्प 1',
      'ml': 'ഓപ്ഷൻ 1',
      'or': 'ବିକଳ୍ପ 1',
      'ta': 'விருப்பம் 1',
      'te': 'ఎంపిక 1',
      'ur': 'آپشن 1',
    },
    '5x8u4g0u': {
      'en': 'All Members',
      'bn': 'সকল সদস্য',
      'hi': 'सभी सदस्य',
      'ml': 'എല്ലാ അംഗങ്ങളും',
      'or': 'ସମସ୍ତ ସଦସ୍ୟ',
      'ta': 'அனைத்து உறுப்பினர்களும்',
      'te': 'సభ్యులందరూ',
      'ur': 'تمام ممبران',
    },
    '4cek35uo': {
      'en': 'View',
      'bn': 'দেখুন',
      'hi': 'देखना',
      'ml': 'കാണുക',
      'or': 'ଦର୍ଶନ କରନ୍ତୁ |',
      'ta': 'காண்க',
      'te': 'చూడండి',
      'ur': 'دیکھیں',
    },
    'mvx2sb5k': {
      'en': 'Home',
      'bn': 'বাড়ি',
      'hi': 'घर',
      'ml': 'വീട്',
      'or': 'ଘର',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'ur': 'گھر',
    },
  },
  // User_Entry
  {
    'caip556j': {
      'en': 'Update User Information',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '37g41rh3': {
      'en': 'User Information',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'an6y5axw': {
      'en': 'The application is fast, easy and only takes about 5 minutes',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'a7w9kce4': {
      'en': 'First Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'phtct7ui': {
      'en': 'First name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hzjdwupc': {
      'en': 'Last Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'o1c5ra49': {
      'en': 'Last Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x9l6w637': {
      'en': 'Change Photo',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ha230vvt': {
      'en': 'Change Photo',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3ukoxgxe': {
      'en': 'Status Type',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ph2vaaxb': {
      'en': 'Stock Portfolio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'or29obg7': {
      'en': 'Trading Portfolio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kc4kwbfu': {
      'en': 'Custom Wallet',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v7qc23zi': {
      'en': '1',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mj7avzds': {
      'en': 'Search for an item...',
      'bn': 'একটি আইটেম খুঁজুন...',
      'hi': 'कोई आइटम खोजें...',
      'ml': 'ഒരു ഇനത്തിനായി തിരയുക...',
      'or': 'ଏକ ଆଇଟମ୍ ପାଇଁ ସନ୍ଧାନ ...',
      'ta': 'ஒரு பொருளைத் தேடு...',
      'te': 'వస్తువు కోసం వెతకండి...',
      'ur': 'ایک آئٹم تلاش کریں...',
    },
    'r0ddtku3': {
      'en': 'Nationality',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kz8snroz': {
      'en': 'Iraqi',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zxmrkbmv': {
      'en': 'South Korean',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fi1wfu83': {
      'en': 'Cambodian',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5kmqhttg': {
      'en': 'Nationality',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nr06xdzu': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x3nbc6wo': {
      'en': 'Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'b6su8y7w': {
      'en': 'Diamond',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4iyd5ssz': {
      'en': 'Diamond Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p1jpng2p': {
      'en': 'Silver Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rtcd7qva': {
      'en': 'Bronze Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bmtz0mp8': {
      'en': 'Gold Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'taq8vg7k': {
      'en': '1',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zgn4hdl3': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8f12y1kw': {
      'en': 'Balance',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x7itvnhs': {
      'en': 'Address....',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lw61q0su': {
      'en': 'Address',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    't2ou2bip': {
      'en': 'Address....',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '28vc9s5b': {
      'en': 'Email',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'y3fg785s': {
      'en': 'Email....',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8ruqefgi': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7updddmx': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ax53ii8l': {
      'en': 'Confirm Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hnbd8ff2': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mskxebw2': {
      'en': 'Role of User',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6ybkmlac': {
      'en': 'ADMINISTRATOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'n3dn306v': {
      'en': 'INVESTOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zrfne89v': {
      'en': 'EDITOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fylmjbmh': {
      'en': 'READ_ONLY',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jszdcyhd': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'blyx02b1': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e0ipd6uh': {
      'en': 'Payment Status',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iqmpxbdb': {
      'en': 'PENDING',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'erwwun1m': {
      'en': 'DONE',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5v5rb48a': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'robrp8zw': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xde0ebce': {
      'en': 'Investment Period',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'atxhfzx4': {
      'en': '3 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'q96x2sv8': {
      'en': '6 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'udbkjzv2': {
      'en': '9 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hjulv9to': {
      'en': '1 year',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ptv68wap': {
      'en': '1',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'jhjll6tm': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'noo4tsec': {
      'en': 'Yield Period',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ozc3i012': {
      'en': '3 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    's6jo0p5s': {
      'en': '6 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l8k0cc4m': {
      'en': '9 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l455wqqw': {
      'en': '12 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'butq7nbh': {
      'en': '1',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iseoh9kk': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5jrpb5fr': {
      'en': 'Risk Ratio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p9bgue70': {
      'en': '0.70',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nk4h75k7': {
      'en': 'Profit Distribution Ratio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '98x6xdbn': {
      'en': '0.70',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vxsau44y': {
      'en': '0.30',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'eimoyufl': {
      'en': 'Date',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qu874d70': {
      'en': 'DD / MM / YYYY',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ywuzwes2': {
      'en': 'Mobile Phone',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bp4100zh': {
      'en': 'Mobile Phone',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1n1yjfm2': {
      'en': 'Note',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'w69ghr5c': {
      'en': 'Type here....',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7x9k1tjo': {
      'en': 'Update Data',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xmttwvqo': {
      'en': 'User Information',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '40oppz6r': {
      'en': 'The application is fast, easy and only takes about 5 minutes',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8n2z5u5n': {
      'en': 'First Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bqbicjhv': {
      'en': 'First name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xaaaxdhc': {
      'en': 'Last Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gdcdokvb': {
      'en': 'Last Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '838mi1yk': {
      'en': 'Change Photo',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '58gioorz': {
      'en': 'Change Photo',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'epbvgqzb': {
      'en': 'Status Type',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'a3s84evs': {
      'en': 'Stock Portfolio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'afobyeyo': {
      'en': 'Trading Portfolio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pkutr2o3': {
      'en': 'Custom Wallet',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'a1iw12i9': {
      'en': 'Portfolio Type',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ov0k7t3g': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0d2bd9to': {
      'en': 'Nationality',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fewxke8g': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9p90yn7z': {
      'en': 'Iraqi',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2z880mhl': {
      'en': 'South Korean',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '32kyszfa': {
      'en': 'Cambodian',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7fzz5gsc': {
      'en': 'Nationality',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'o76j7x4z': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l7jpfpc3': {
      'en': 'Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'akdz0gpw': {
      'en': 'Diamond',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rdykqxxj': {
      'en': 'Bronze Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g7rno9d1': {
      'en': 'Silver Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tgrlu1tr': {
      'en': 'Gold Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mp9f85zl': {
      'en': 'Diamond Package',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9t75rpbs': {
      'en': 'Package...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j4shsw6z': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8u0e3x5f': {
      'en': 'Address',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lkpmpira': {
      'en': 'Address....',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4cjvkfc8': {
      'en': 'Email',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8i4krgcn': {
      'en': 'Email',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g8mz2inm': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4vpcygf2': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nvdhrygz': {
      'en': 'Field is required',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'y2hb3z9k': {
      'en': 'has to be valid Email',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '45felak1': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vigozjl4': {
      'en': 'Field is required',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pf5dfzkc': {
      'en': 'Please choose an option from the dropdown',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5rcyh6dz': {
      'en': 'Confirm Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j6pn0pe8': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '384mnmdg': {
      'en': 'Role of User',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kanm476c': {
      'en': 'ADMINISTRATOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ise63je7': {
      'en': 'ADMINISTRATOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ki0pbhtd': {
      'en': 'INVESTOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vpbcfwpb': {
      'en': 'EDITOR',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'crgtfccp': {
      'en': 'READ_ONLY',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ghb6kglt': {
      'en': 'Role',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'h3zq9gz6': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4rs9vyh8': {
      'en': 'Payment Status',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bwrms91c': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2w5dkdd4': {
      'en': 'PENDING',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'y7cks1e5': {
      'en': 'DONE',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pbnbszy3': {
      'en': 'Status',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3jajl3cu': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bl2f9jbe': {
      'en': 'Investment Period',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'zcjsultl': {
      'en': '3 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '19fwovhp': {
      'en': '6 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4t6mir4i': {
      'en': '9 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'y7enbnr4': {
      'en': '1 year',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'w0d8w3kl': {
      'en': 'Select Investment period',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iio1ncus': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'x0mqjzik': {
      'en': 'Yield Period',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nxs4wpj7': {
      'en': '3 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7auxqwil': {
      'en': '6 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p9g37j3m': {
      'en': '9 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5ggeetgr': {
      'en': '12 months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8a1t7s02': {
      'en': 'Select Yield Period',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '943czd5h': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hm6pygwe': {
      'en': 'Risk Ratio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'eycoxtu6': {
      'en': '0.70',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'idgmy93v': {
      'en': 'Profit Distribution Ratio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ih087sjc': {
      'en': '0.70',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5hczm9b7': {
      'en': '0.30',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rhnyyz6b': {
      'en': 'Date of Birth',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'z2vqvpx7': {
      'en': 'DD / MM / YYYY',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9iuk5lc3': {
      'en': 'Mobile Phone',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xg9ke738': {
      'en': 'Mobile Phone',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lj58yyhx': {
      'en': 'Note',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vs5l22vw': {
      'en': 'Type here....',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qg10x3li': {
      'en': 'Create User',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4p8ptjui': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Company_Entry
  {
    't3x1fouh': {
      'en': 'Investment Data',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u3pkskx2': {
      'en': 'Bulk data',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uxoud9p7': {
      'en': 'Monthly Data',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l62fal37': {
      'en': 'Download sample file',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '53t9cvmh': {
      'en': 'Monthly Data Information',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ik8a3a6a': {
      'en': 'This form allows you to input data of an investment.',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5586pcqe': {
      'en': 'Investor Evaluation',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'shvm76ef': {
      'en': '100',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rej1df0d': {
      'en': 'Balance',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ftudbown': {
      'en': '100',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ld8nccco': {
      'en': 'Points',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2ulbjpxm': {
      'en': '1050',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yzi94nw1': {
      'en': 'Investors Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6hhu7brf': {
      'en': 'Name...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'uj4s20rn': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xhzvxtei': {
      'en': 'Amount',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2m4unnmq': {
      'en': '\$1050',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3izhwmtg': {
      'en': 'Date',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g9p0jw3g': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ugf7lg0m': {
      'en': 'Profit Ratio',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kip0v0w0': {
      'en': '5 %',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'rhve4end': {
      'en': 'Transaction Type',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'u10k7k94': {
      'en': 'Profit',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hjotckff': {
      'en': 'Commission',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8yaiaz6l': {
      'en': 'Deposit',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '44x47uon': {
      'en': 'Transaction Type',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5i3x0zzp': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dwlrrx1f': {
      'en': 'Duration',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'i23063tt': {
      'en': '3 Months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lrum1is6': {
      'en': '6 Months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bny76p4z': {
      'en': '9 Months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7bjnw7hu': {
      'en': '12 Months',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '30gidaoy': {
      'en': 'Duration',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'c3o473db': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iy8k83ai': {
      'en': 'Create  Data',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'txrqj8re': {
      'en': 'company_Entry',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // ListUserNLog
  {
    'ecazn4fx': {
      'en': 'Dashboard',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '0kyywvfm': {
      'en': 'Log List',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fwhqxlb7': {
      'en': 'Log Activity',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'pa4upme9': {
      'en': 'Below is the list of all Log.',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vy49suw6': {
      'en': 'All',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '1gvcsl3j': {
      'en': 'All',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e2mdsak5': {
      'en': 'UPDATE_USER',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '30v1s10h': {
      'en': 'LOGIN',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'oou86oat': {
      'en': 'CREATE_INVESTMENT_DATA',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qo672yzp': {
      'en': 'LOGOUT',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'l5qf22ye': {
      'en': 'EDIT_PROFILE',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'g14bey1l': {
      'en': 'UPDATE_USER',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tnmwzhxw': {
      'en': 'All',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '3g7zxecs': {
      'en': 'All',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qdc0vnhz': {
      'en': 'Search all User...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lf3hued6': {
      'en': 'User List',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6mn2u3du': {
      'en': 'Investment Data',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'byjsdplw': {
      'en': 'This is the summary of Users',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bb3w2qk8': {
      'en': 'Search all User...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2od3b945': {
      'en': 'Investment List',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'k8auerai': {
      'en': 'Investment list',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p40v20eo': {
      'en': 'Type of Transaction',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '92unqu4y': {
      'en': 'Amount',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'qjilyqkv': {
      'en': 'Duration',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '7izb3z7x': {
      'en': 'Created Date',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4y54m5k6': {
      'en': 'Investor',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ec7p3eb4': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // modal_Message
  {
    'wa4vkne2': {
      'en': 'Congratulations!',
      'bn': 'অভিনন্দন!',
      'hi': 'बधाई हो!',
      'ml': 'അഭിനന്ദനങ്ങൾ!',
      'or': 'ଅଭିନନ୍ଦନ!',
      'ta': 'வாழ்த்துகள்!',
      'te': 'అభినందనలు!',
      'ur': 'مبارک ہو!',
    },
    '3hf2ocig': {
      'en':
          'Now that a contract has been generated for this customer please contact them with the date you will send the signed agreement.',
      'bn':
          'এখন যেহেতু এই গ্রাহকের জন্য একটি চুক্তি তৈরি হয়েছে অনুগ্রহ করে তাদের সাথে যোগাযোগ করুন যে তারিখে আপনি স্বাক্ষরিত চুক্তিটি পাঠাবেন৷',
      'hi':
          'अब जब इस ग्राहक के लिए एक अनुबंध तैयार हो गया है तो कृपया उनसे उस तारीख के साथ संपर्क करें जिस पर आप हस्ताक्षरित अनुबंध भेजेंगे।',
      'ml':
          'ഇപ്പോൾ ഈ ഉപഭോക്താവിനായി ഒരു കരാർ സൃഷ്ടിച്ചിരിക്കുന്നു, നിങ്ങൾ ഒപ്പിട്ട കരാർ അയയ്‌ക്കുന്ന തീയതിയുമായി അവരെ ബന്ധപ്പെടുക.',
      'or':
          'ବର୍ତ୍ତମାନ ଯେହେତୁ ଏହି ଗ୍ରାହକଙ୍କ ପାଇଁ ଏକ ଚୁକ୍ତିନାମା ସୃଷ୍ଟି ହୋଇଛି ଦୟାକରି ଆପଣ ସ୍ୱାକ୍ଷରିତ ଚୁକ୍ତିନାମା ପଠାଇବାର ତାରିଖ ସହିତ ସେମାନଙ୍କ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ |',
      'ta':
          'இப்போது இந்த வாடிக்கையாளருக்கான ஒப்பந்தம் உருவாக்கப்பட்டுள்ளது, நீங்கள் கையெழுத்திட்ட ஒப்பந்தத்தை அனுப்பும் தேதியுடன் அவர்களைத் தொடர்பு கொள்ளவும்.',
      'te':
          'ఇప్పుడు ఈ కస్టమర్ కోసం ఒక ఒప్పందం రూపొందించబడింది, దయచేసి మీరు సంతకం చేసిన ఒప్పందాన్ని పంపే తేదీతో వారిని సంప్రదించండి.',
      'ur':
          'اب جب کہ اس صارف کے لیے ایک معاہدہ تیار کیا گیا ہے، براہ کرم ان سے اس تاریخ کے ساتھ رابطہ کریں جب آپ دستخط شدہ معاہدہ بھیجیں گے۔',
    },
    'q0jvi1lp': {
      'en': 'Okay',
      'bn': 'ঠিক আছে',
      'hi': 'ठीक',
      'ml': 'ശരി',
      'or': 'ଠିକ ଅଛି',
      'ta': 'சரி',
      'te': 'సరే',
      'ur': 'ٹھیک ہے',
    },
    'oo4y13nf': {
      'en': 'Continue',
      'bn': 'চালিয়ে যান',
      'hi': 'जारी रखना',
      'ml': 'തുടരുക',
      'or': 'ଜାରି ରଖ |',
      'ta': 'தொடரவும்',
      'te': 'కొనసాగించు',
      'ur': 'جاری رہے',
    },
  },
  // modal_Welcome
  {
    '00flvi93': {
      'en': 'Congratulations!',
      'bn': 'অভিনন্দন!',
      'hi': 'बधाई हो!',
      'ml': 'അഭിനന്ദനങ്ങൾ!',
      'or': 'ଅଭିନନ୍ଦନ!',
      'ta': 'வாழ்த்துகள்!',
      'te': 'అభినందనలు!',
      'ur': 'مبارک ہو!',
    },
    'fmzceh74': {
      'en': 'A new contract has been generated for:',
      'bn': 'এর জন্য একটি নতুন চুক্তি তৈরি করা হয়েছে:',
      'hi': 'इसके लिए एक नया अनुबंध तैयार किया गया है:',
      'ml': 'ഇതിനായി ഒരു പുതിയ കരാർ സൃഷ്ടിച്ചു:',
      'or': 'ଏଥିପାଇଁ ଏକ ନୂତନ ଚୁକ୍ତିନାମା ସୃଷ୍ଟି ହୋଇଛି:',
      'ta': 'ஒரு புதிய ஒப்பந்தம் உருவாக்கப்பட்டுள்ளது:',
      'te': 'దీని కోసం కొత్త ఒప్పందం రూపొందించబడింది:',
      'ur': 'ایک نیا معاہدہ اس کے لیے تیار کیا گیا ہے:',
    },
    'g8q2u55w': {
      'en': 'Continue',
      'bn': 'চালিয়ে যান',
      'hi': 'जारी रखना',
      'ml': 'തുടരുക',
      'or': 'ଜାରି ରଖ |',
      'ta': 'தொடரவும்',
      'te': 'కొనసాగించు',
      'ur': 'جاری رہے',
    },
  },
  // createComment
  {
    'l2jlnhye': {
      'en': 'Create Note',
      'bn': 'নোট তৈরি করুন',
      'hi': 'नोट बनाएं',
      'ml': 'കുറിപ്പ് സൃഷ്ടിക്കുക',
      'or': 'ଟିପ୍ପଣୀ ସୃଷ୍ଟି କରନ୍ତୁ |',
      'ta': 'குறிப்பை உருவாக்கவும்',
      'te': 'గమనికను సృష్టించండి',
      'ur': 'نوٹ بنائیں',
    },
    'd6yfe8tj': {
      'en': 'Find members by searching below',
      'bn': 'নীচে অনুসন্ধান করে সদস্যদের খুঁজুন',
      'hi': 'नीचे खोजकर सदस्यों को ढूंढें',
      'ml': 'താഴെ തിരയുന്നതിലൂടെ അംഗങ്ങളെ കണ്ടെത്തുക',
      'or': 'ନିମ୍ନରେ ସନ୍ଧାନ କରି ସଦସ୍ୟ ଖୋଜ |',
      'ta': 'கீழே தேடுவதன் மூலம் உறுப்பினர்களைக் கண்டறியவும்',
      'te': 'దిగువ శోధించడం ద్వారా సభ్యులను కనుగొనండి',
      'ur': 'ذیل میں تلاش کرکے اراکین کو تلاش کریں۔',
    },
    'p3rj5ra0': {
      'en': 'Ricky Rodriguez',
      'bn': 'রিকি রদ্রিগেজ',
      'hi': 'रिकी रोड्रिग्ज',
      'ml': 'റിക്കി റോഡ്രിഗസ്',
      'or': 'ରିକି ରୋଡ୍ରିଗେଜ୍ |',
      'ta': 'ரிக்கி ரோட்ரிக்ஸ்',
      'te': 'రికీ రోడ్రిగ్జ్',
      'ur': 'رکی روڈریگز',
    },
    '9gf6o5ss': {
      'en': 'Enter your note here...',
      'bn': 'এখানে আপনার নোট লিখুন...',
      'hi': 'अपना नोट यहां दर्ज करें...',
      'ml': 'നിങ്ങളുടെ കുറിപ്പ് ഇവിടെ നൽകുക...',
      'or': 'ଏଠାରେ ଆପଣଙ୍କର ନୋଟ୍ ପ୍ରବେଶ କରନ୍ତୁ ...',
      'ta': 'உங்கள் குறிப்பை இங்கே உள்ளிடவும்...',
      'te': 'మీ గమనికను ఇక్కడ నమోదు చేయండి...',
      'ur': 'اپنا نوٹ یہاں درج کریں...',
    },
    'farrki57': {
      'en': 'Create Note',
      'bn': 'নোট তৈরি করুন',
      'hi': 'नोट बनाएं',
      'ml': 'കുറിപ്പ് സൃഷ്ടിക്കുക',
      'or': 'ଟିପ୍ପଣୀ ସୃଷ୍ଟି କରନ୍ତୁ |',
      'ta': 'குறிப்பை உருவாக்கவும்',
      'te': 'గమనికను సృష్టించండి',
      'ur': 'نوٹ بنائیں',
    },
  },
  // commandPalette
  {
    'jt9g5o8v': {
      'en': 'Search platform...',
      'bn': 'অনুসন্ধান প্ল্যাটফর্ম...',
      'hi': 'खोज मंच...',
      'ml': 'തിരയൽ പ്ലാറ്റ്ഫോം...',
      'or': 'ସନ୍ଧାନ ପ୍ଲାଟଫର୍ମ ...',
      'ta': 'தேடல் தளம்...',
      'te': 'శోధన వేదిక...',
      'ur': 'پلیٹ فارم تلاش کریں...',
    },
    'b3bd9y8w': {
      'en': 'Search',
      'bn': 'অনুসন্ধান করুন',
      'hi': 'खोज',
      'ml': 'തിരയുക',
      'or': 'ସନ୍ଧାନ କର |',
      'ta': 'தேடு',
      'te': 'వెతకండి',
      'ur': 'تلاش کریں۔',
    },
    'pw6kvl1f': {
      'en': 'Quick Links',
      'bn': 'দ্রুত লিঙ্ক',
      'hi': 'त्वरित सम्पक',
      'ml': 'ദ്രുത ലിങ്കുകൾ',
      'or': 'ଦ୍ରୁତ ଲିଙ୍କ୍ |',
      'ta': 'விரைவு இணைப்புகள்',
      'te': 'త్వరిత లింక్‌లు',
      'ur': 'فوری رابطے',
    },
    'gckukxjv': {
      'en': 'Add Quiz',
      'bn': 'চুক্তি খুঁজুন',
      'hi': 'अनुबंध खोजें',
      'ml': 'കരാർ കണ്ടെത്തുക',
      'or': 'ଚୁକ୍ତିନାମା ଖୋଜ |',
      'ta': 'ஒப்பந்தத்தைக் கண்டறியவும்',
      'te': 'ఒప్పందాన్ని కనుగొనండి',
      'ur': 'معاہدہ تلاش کریں۔',
    },
    'zsq8vj02': {
      'en': 'Find Customer',
      'bn': 'গ্রাহক খুঁজুন',
      'hi': 'ग्राहक खोजें',
      'ml': 'ഉപഭോക്താവിനെ കണ്ടെത്തുക',
      'or': 'ଗ୍ରାହକ ଖୋଜ |',
      'ta': 'வாடிக்கையாளரைக் கண்டறியவும்',
      'te': 'కస్టమర్‌ని కనుగొనండి',
      'ur': 'گاہک تلاش کریں۔',
    },
    'iqxwv326': {
      'en': 'New Project',
      'bn': 'নতুন প্রকল্প',
      'hi': 'नया काम',
      'ml': 'പുതിയ പദ്ധതി',
      'or': 'ନୂତନ ପ୍ରକଳ୍ପ',
      'ta': 'புதிய திட்டம்',
      'te': 'కొత్త ప్రాజెక్ట్',
      'ur': 'نیا کام',
    },
    's60yfg0g': {
      'en': 'New Customer',
      'bn': 'নতুন গ্রাহক',
      'hi': 'नए ग्राहक',
      'ml': 'പുതിയ ഉപഭോക്താവ്',
      'or': 'ନୂତନ ଗ୍ରାହକ |',
      'ta': 'புதிய வாடிக்கையாளர்',
      'te': 'కొత్త కస్టమర్',
      'ur': 'نیا گاہک',
    },
  },
  // editProfilePhoto
  {
    '6bnefz1c': {
      'en': 'Change Photo',
      'bn': 'ছবি পরিবর্তন',
      'hi': 'छवि बदलो',
      'ml': 'ചിത്രം മാറ്റുക',
      'or': 'ଫଟୋ ପରିବର୍ତ୍ତନ କରନ୍ତୁ |',
      'ta': 'புகைப்படத்தை மாற்று',
      'te': 'ఫోటో మార్చు',
      'ur': 'تصویر تبدیل کریں',
    },
    'yaxe7q8v': {
      'en':
          'Upload a new photo below in order to change your avatar seen by others.',
      'bn':
          'অন্যদের দ্বারা দেখা আপনার অবতার পরিবর্তন করার জন্য নীচে একটি নতুন ফটো আপলোড করুন৷',
      'hi':
          'दूसरों द्वारा देखे गए अपने अवतार को बदलने के लिए नीचे एक नई फ़ोटो अपलोड करें।',
      'ml':
          'മറ്റുള്ളവർ കാണുന്ന നിങ്ങളുടെ അവതാർ മാറ്റുന്നതിന് ചുവടെ ഒരു പുതിയ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക.',
      'or':
          'ଅନ୍ୟମାନଙ୍କ ଦ୍ୱାରା ଦେଖାଯାଇଥିବା ଆପଣଙ୍କର ଅବତାର ପରିବର୍ତ୍ତନ କରିବାକୁ ନିମ୍ନରେ ଏକ ନୂତନ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ |',
      'ta':
          'மற்றவர்கள் பார்க்கும் உங்கள் அவதாரத்தை மாற்ற, கீழே ஒரு புதிய புகைப்படத்தைப் பதிவேற்றவும்.',
      'te':
          'ఇతరులు చూసిన మీ అవతార్‌ని మార్చడానికి దిగువన కొత్త ఫోటోను అప్‌లోడ్ చేయండి.',
      'ur':
          'دوسروں کے ذریعے دیکھے گئے اپنے اوتار کو تبدیل کرنے کے لیے نیچے ایک نئی تصویر اپ لوڈ کریں۔',
    },
    're4x0sz7': {
      'en': 'Upload Image',
      'bn': 'চিত্র আপলোড',
      'hi': 'तस्विर अपलोड करना',
      'ml': 'ചിത്രം അപ്ലോഡ് ചെയ്യുക',
      'or': 'ପ୍ରତିଛବି ଅପଲୋଡ୍ କରନ୍ତୁ |',
      'ta': 'படத்தை பதிவேற்றம் செய்யவும்',
      'te': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
      'ur': 'تصویر انٹرنیٹ پر ڈالنا',
    },
    'sr54fsk6': {
      'en': 'Save Changes',
      'bn': 'পরিবর্তনগুলোর সংরক্ষন',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ml': 'മാറ്റങ്ങൾ സൂക്ഷിക്കുക',
      'or': 'ପରିବର୍ତ୍ତନଗୁଡିକ ସଞ୍ଚୟ କରନ୍ତୁ |',
      'ta': 'மாற்றங்களை சேமியுங்கள்',
      'te': 'మార్పులను ఊంచు',
      'ur': 'تبدیلیاں محفوظ کرو',
    },
  },
  // user_Details_main
  {
    '534e9fmv': {
      'en': 'High Profile',
      'bn': 'উচ্চ পদস্ত',
      'hi': 'उच्च प्रोफ़ाइल',
      'ml': 'ഉയർന്ന പ്രൊഫൈൽ',
      'or': 'ଉଚ୍ଚ ପ୍ରୋଫାଇଲ୍ |',
      'ta': 'உயர் சுயவிவரம்',
      'te': 'హై ప్రొఫైల్',
      'ur': 'ہائی پروفائل',
    },
    'jindju5a': {
      'en': 'Phone Number',
      'bn': 'শিরোনাম',
      'hi': 'शीर्षक',
      'ml': 'തലക്കെട്ട്',
      'or': 'ଆଖ୍ୟା',
      'ta': 'தலைப்பு',
      'te': 'శీర్షిక',
      'ur': 'عنوان',
    },
    '8viyn84n': {
      'en': 'Date',
      'bn': 'প্রতিষ্ঠান',
      'hi': 'कंपनी',
      'ml': 'കമ്പനി',
      'or': 'କମ୍ପାନୀ',
      'ta': 'நிறுவனம்',
      'te': 'కంపెనీ',
      'ur': 'کمپنی',
    },
  },
  // modal_CreateProject
  {
    '5tdm3cpv': {
      'en': 'Create Project',
      'bn': 'প্রকল্প তৈরি করুন',
      'hi': 'प्रोजेक्ट बनाएं',
      'ml': 'പ്രോജക്റ്റ് സൃഷ്ടിക്കുക',
      'or': 'ପ୍ରୋଜେକ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ |',
      'ta': 'திட்டத்தை உருவாக்கவும்',
      'te': 'ప్రాజెక్ట్ సృష్టించండి',
      'ur': 'پروجیکٹ بنائیں',
    },
    'vlg015ed': {
      'en': 'Please enter the information below to add a project.',
      'bn': 'একটি প্রকল্প যোগ করার জন্য নীচের তথ্য লিখুন.',
      'hi': 'कृपया कोई प्रोजेक्ट जोड़ने के लिए नीचे दी गई जानकारी दर्ज करें।',
      'ml': 'ഒരു പ്രോജക്‌റ്റ് ചേർക്കുന്നതിന് ചുവടെയുള്ള വിവരങ്ങൾ നൽകുക.',
      'or': 'ଏକ ପ୍ରୋଜେକ୍ଟ ଯୋଡିବାକୁ ଦୟାକରି ନିମ୍ନରେ ସୂଚନା ପ୍ରବେଶ କରନ୍ତୁ |',
      'ta': 'திட்டத்தைச் சேர்க்க கீழே உள்ள தகவலை உள்ளிடவும்.',
      'te':
          'ప్రాజెక్ట్‌ను జోడించడానికి దయచేసి దిగువన ఉన్న సమాచారాన్ని నమోదు చేయండి.',
      'ur':
          'براہ کرم ایک پروجیکٹ شامل کرنے کے لیے نیچے دی گئی معلومات درج کریں۔',
    },
    'dqo5yhdb': {
      'en': 'Add Photo',
      'bn': 'ঘফজ',
      'hi': 'तस्वीर जोड़ो',
      'ml': 'ഫോട്ടോ ചേർക്കുക',
      'or': 'ଫଟୋ ଯୋଡନ୍ତୁ |',
      'ta': 'புகைப்படம் சேர்க்க',
      'te': 'ఫోటోను జోడించండి',
      'ur': 'تصویر لگاو',
    },
    '426hn69e': {
      'en': 'Project Name',
      'bn': 'প্রকল্পের নাম',
      'hi': 'परियोजना का नाम',
      'ml': 'പദ്ധതിയുടെ പേര്',
      'or': 'ପ୍ରକଳ୍ପ ନାମ',
      'ta': 'திட்டத்தின் பெயர்',
      'te': 'ప్రాజెక్ట్ పేరు',
      'ur': 'پراجیکٹ کا نام',
    },
    'uqziqhmg': {
      'en': 'Description here...',
      'bn': 'বর্ণনা এখানে...',
      'hi': 'विवरण यहाँ...',
      'ml': 'വിവരണം ഇവിടെ...',
      'or': 'ଏଠାରେ ବର୍ଣ୍ଣନା ...',
      'ta': 'விளக்கம் இங்கே...',
      'te': 'వివరణ ఇక్కడ...',
      'ur': 'تفصیل یہاں...',
    },
    'rsj2kx34': {
      'en': 'Create Project',
      'bn': 'প্রকল্প তৈরি করুন',
      'hi': 'प्रोजेक्ट बनाएं',
      'ml': 'പ്രോജക്റ്റ് സൃഷ്ടിക്കുക',
      'or': 'ପ୍ରୋଜେକ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ |',
      'ta': 'திட்டத்தை உருவாக்கவும்',
      'te': 'ప్రాజెక్ట్ సృష్టించండి',
      'ur': 'پروجیکٹ بنائیں',
    },
    '4spmowtt': {
      'en': 'Please enter a project name...',
      'bn': 'অনুগ্রহ করে একটি প্রকল্পের নাম লিখুন...',
      'hi': 'कृपया प्रोजेक्ट का नाम दर्ज करें...',
      'ml': 'ദയവായി ഒരു പദ്ധതിയുടെ പേര് നൽകുക...',
      'or': 'ଦୟାକରି ଏକ ପ୍ରକଳ୍ପ ନାମ ପ୍ରବେଶ କରନ୍ତୁ ...',
      'ta': 'திட்டப் பெயரை உள்ளிடவும்...',
      'te': 'దయచేసి ప్రాజెక్ట్ పేరును నమోదు చేయండి...',
      'ur': 'براہ کرم پروجیکٹ کا نام درج کریں...',
    },
    '32kj9709': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প চয়ন করুন',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'ml': 'ഡ്രോപ്പ്ഡൗണിൽ നിന്ന് ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
      'or': 'ଦୟାକରି ଡ୍ରପଡାଉନରୁ ଏକ ବିକଳ୍ପ ବାଛନ୍ତୁ |',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి',
      'ur': 'براہ کرم ڈراپ ڈاؤن سے ایک آپشن منتخب کریں۔',
    },
    'wfu6up0n': {
      'en': 'Please enter a short description...',
      'bn': 'অনুগ্রহ করে একটি সংক্ষিপ্ত বিবরণ লিখুন...',
      'hi': 'कृपया संक्षिप्त विवरण दर्ज करें...',
      'ml': 'ദയവായി ഒരു ചെറിയ വിവരണം നൽകുക...',
      'or': 'ଦୟାକରି ଏକ ସଂକ୍ଷିପ୍ତ ବର୍ଣ୍ଣନା ପ୍ରବେଶ କରନ୍ତୁ ...',
      'ta': 'ஒரு சிறிய விளக்கத்தை உள்ளிடவும்...',
      'te': 'దయచేసి చిన్న వివరణను నమోదు చేయండి...',
      'ur': 'براہ کرم ایک مختصر تفصیل درج کریں...',
    },
    'qt5dp4ez': {
      'en': 'Please choose an option from the dropdown',
      'bn': 'ড্রপডাউন থেকে একটি বিকল্প চয়ন করুন',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'ml': 'ഡ്രോപ്പ്ഡൗണിൽ നിന്ന് ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
      'or': 'ଦୟାକରି ଡ୍ରପଡାଉନରୁ ଏକ ବିକଳ୍ପ ବାଛନ୍ତୁ |',
      'ta': 'கீழ்தோன்றலில் இருந்து ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి',
      'ur': 'براہ کرم ڈراپ ڈاؤن سے ایک آپشن منتخب کریں۔',
    },
  },
  // modal_profile_Details
  {
    'xt43uwzp': {
      'en': 'Profile Details',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '9ren6rbd': {
      'en': 'Below are your profile details',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '5bzj3jf4': {
      'en': 'Manage your account',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wbiu740t': {
      'en': 'Light Mode',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    's5971e7s': {
      'en': 'Dark Mode',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'riwckyhb': {
      'en': 'Close',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'trmvrg86': {
      'en': 'Logout',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // modal_profile_Edit
  {
    'qs8serr4': {
      'en': 'Edit Profile',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'bvy3fs93': {
      'en': 'Below are your profile details',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'nx89dnuw': {
      'en': 'Change Photo',
      'bn': 'ছবি পরিবর্তন',
      'hi': 'छवि बदलो',
      'ml': 'ചിത്രം മാറ്റുക',
      'or': 'ଫଟୋ ପରିବର୍ତ୍ତନ କରନ୍ତୁ |',
      'ta': 'புகைப்படத்தை மாற்று',
      'te': 'ఫోటో మార్చు',
      'ur': 'تصویر تبدیل کریں',
    },
    '99oumm34': {
      'en': 'Your Name',
      'bn': 'তোমার নাম',
      'hi': 'अप का नाम',
      'ml': 'നിങ്ങളുടെ പേര്',
      'or': 'ତୁମର ନାମ',
      'ta': 'உங்கள் பெயர்',
      'te': 'నీ పేరు',
      'ur': 'تمھارا نام',
    },
    '8gkrs3rw': {
      'en': 'Short Description',
      'bn': 'তোমার নাম',
      'hi': 'अप का नाम',
      'ml': 'നിങ്ങളുടെ പേര്',
      'or': 'ତୁମର ନାମ',
      'ta': 'உங்கள் பெயர்',
      'te': 'నీ పేరు',
      'ur': 'تمھارا نام',
    },
    'au9c3fpx': {
      'en': 'ADMINISTRATOR',
      'bn': 'কলিং',
      'hi': 'कॉलिंग',
      'ml': 'വിളിക്കുന്നു',
      'or': 'କଲ୍ କରୁଛି |',
      'ta': 'அழைப்பு',
      'te': 'పిలుస్తోంది',
      'ur': 'کال کرنا',
    },
    '6qzm16cz': {
      'en': 'INVESTOR',
      'bn': 'ডাকা হয়নি',
      'hi': 'नहीं बुलाया गया',
      'ml': 'വിളിച്ചിട്ടില്ല',
      'or': 'କଲ୍ ହୋଇନାହିଁ |',
      'ta': 'அழைக்கப்படவில்லை',
      'te': 'పిలవలేదు',
      'ur': 'نہیں بلایا',
    },
    '6xjfeugp': {
      'en': 'READ_ONLY',
      'bn': 'মুলতুবি পর্যালোচনা',
      'hi': 'लंबित समीक्षा',
      'ml': 'അവശേഷിക്കുന്ന നിരൂപണം',
      'or': 'ବିଚାରାଧୀନ ସମୀକ୍ଷା',
      'ta': 'மதிப்பாய்வு நிலுவையில் உள்ளது',
      'te': 'పెండింగ్ రివ్యూ',
      'ur': 'زیر التواء جائزہ',
    },
    '4ga29wxb': {
      'en': 'EDITOR',
      'bn': 'বন্ধ',
      'hi': 'बंद किया हुआ',
      'ml': 'അടച്ചു',
      'or': 'ବନ୍ଦ |',
      'ta': 'மூடப்பட்டது',
      'te': 'మూసివేయబడింది',
      'ur': 'بند',
    },
    'r971lmjm': {
      'en': 'Please select...',
      'bn': 'অনুগ্রহ করে নির্বাচন করুন...',
      'hi': 'कृपया चयन कीजिए...',
      'ml': 'ദയവായി തിരഞ്ഞെടുക്കുക...',
      'or': 'ଦୟାକରି ଚୟନ କରନ୍ତୁ ...',
      'ta': 'தயவு செய்து தேர்வு செய்யவும்...',
      'te': 'దయచేసి ఎంచుకోండి...',
      'ur': 'براہ مہربانی منتخب کریں...',
    },
    '1c8v9uhp': {
      'en': 'Search for an item...',
      'bn': 'একটি আইটেম খুঁজুন...',
      'hi': 'कोई आइटम खोजें...',
      'ml': 'ഒരു ഇനത്തിനായി തിരയുക...',
      'or': 'ଏକ ଆଇଟମ୍ ପାଇଁ ସନ୍ଧାନ ...',
      'ta': 'ஒரு பொருளைத் தேடு...',
      'te': 'వస్తువు కోసం వెతకండి...',
      'ur': 'ایک آئٹم تلاش کریں...',
    },
    'p1lquhce': {
      'en': 'The email associated with this account is:',
      'bn': 'এই অ্যাকাউন্টের সাথে যুক্ত ইমেল হল:',
      'hi': 'इस खाते से संबद्ध ईमेल है:',
      'ml': 'ഈ അക്കൗണ്ടുമായി ബന്ധപ്പെട്ട ഇമെയിൽ ഇതാണ്:',
      'or': 'ଏହି ଖାତା ସହିତ ଜଡିତ ଇମେଲ୍ ହେଉଛି:',
      'ta': 'இந்தக் கணக்குடன் தொடர்புடைய மின்னஞ்சல்:',
      'te': 'ఈ ఖాతాతో అనుబంధించబడిన ఇమెయిల్:',
      'ur': 'اس اکاؤنٹ سے منسلک ای میل یہ ہے:',
    },
    'fyuvtufe': {
      'en': 'Created On:',
      'bn': 'এই অ্যাকাউন্টের সাথে যুক্ত ইমেল হল:',
      'hi': 'इस खाते से संबद्ध ईमेल है:',
      'ml': 'ഈ അക്കൗണ്ടുമായി ബന്ധപ്പെട്ട ഇമെയിൽ ഇതാണ്:',
      'or': 'ଏହି ଖାତା ସହିତ ଜଡିତ ଇମେଲ୍ ହେଉଛି:',
      'ta': 'இந்தக் கணக்குடன் தொடர்புடைய மின்னஞ்சல்:',
      'te': 'ఈ ఖాతాతో అనుబంధించబడిన ఇమెయిల్:',
      'ur': 'اس اکاؤنٹ سے منسلک ای میل یہ ہے:',
    },
    '27w5o6gn': {
      'en': 'Cancel',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'gz2xhplu': {
      'en': 'Save Changes',
      'bn': 'পরিবর্তনগুলোর সংরক্ষন',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ml': 'മാറ്റങ്ങൾ സൂക്ഷിക്കുക',
      'or': 'ପରିବର୍ତ୍ତନଗୁଡିକ ସଞ୍ଚୟ କରନ୍ତୁ |',
      'ta': 'மாற்றங்களை சேமியுங்கள்',
      'te': 'మార్పులను ఊంచు',
      'ur': 'تبدیلیاں محفوظ کرو',
    },
  },
  // Sample_fileDownload
  {
    'uywie35j': {
      'en': 'Download Sample File.xlsx',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // upload_page
  {
    'r24z20jr': {
      'en': 'Upload files',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'saq6vbqx': {
      'en': 'Select and upload the files of your choice',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e59dl8b7': {
      'en': 'Choose User',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'm25mne2d': {
      'en': 'Search for an item...',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j99c87ez': {
      'en': 'Choose a file or drag & drop it here',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8uxe41b7': {
      'en': '.xlsx, .xlsm and .xltx formats, up to 50MB',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'yvm9kbwv': {
      'en': 'Browse File',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4syrj65e': {
      'en': 'my-Data.xlsx',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ok78qct2': {
      'en': '120 KB of 120 KB •',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'vrt8s1s8': {
      'en': 'Completed',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // logPage
  {
    'lfgo6uyz': {
      'en': 'Notification',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // user_Details_mainCopy
  {
    '9gb8ugy5': {
      'en': 'Customer Name',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ggdscbga': {
      'en': 'Randy Alcorn',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'lcft22pd': {
      'en': 'High Profile',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dwjex36d': {
      'en': 'Title',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'wpu2lecy': {
      'en': 'Head of Procurement',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'udh6zyvi': {
      'en': 'Company',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'irzuvqx8': {
      'en': 'ACME Co.',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '4xonfnty': {
      'en': 'Notes',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'j5wv3irx': {
      'en': 'Alexandria Smith',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'mwdngs21': {
      'en': '1m ago',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'infd3htl': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'd8lnj6az': {
      'en': '8',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ybwf7jdv': {
      'en': 'Notes',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e3v0bl1k': {
      'en': 'Randy Alcorn',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'h9er2bef': {
      'en':
          'I\'m not really sure about this section here aI think you should do soemthing cool!',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '29dmpgcv': {
      'en': 'a min ago',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'tov21pqn': {
      'en': 'Generate Quote',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v63bug8g': {
      'en': 'View Company',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
  // Miscellaneous
  {
    '0nwoj0kc': {
      'en': 'Email address',
      'bn': 'ইমেইল ঠিকানা',
      'hi': 'मेल पता',
      'ml': 'ഇമെയിൽ വിലാസം',
      'or': 'ଈମୈଲ ଠିକଣା',
      'ta': 'மின்னஞ்சல் முகவரி',
      'te': 'ఇమెయిల్ చిరునామా',
      'ur': 'ای میل اڈریس',
    },
    'upni203i': {
      'en': 'Password',
      'bn': 'পাসওয়ার্ড',
      'hi': 'पासवर्ड',
      'ml': 'Password',
      'or': 'ପାସୱାର୍ଡ',
      'ta': 'கடவுச்சொல்',
      'te': 'పాస్వర్డ్',
      'ur': 'پاس ورڈ',
    },
    'x5hsigqw': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    '9wy77t9v': {
      'en': 'Button',
      'bn': 'প্রকল্প তৈরি করুন',
      'hi': 'प्रोजेक्ट बनाएं',
      'ml': 'പ്രോജക്റ്റ് സൃഷ്ടിക്കുക',
      'or': 'ପ୍ରୋଜେକ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ |',
      'ta': 'திட்டத்தை உருவாக்கவும்',
      'te': 'ప్రాజెక్ట్ సృష్టించండి',
      'ur': 'پروجیکٹ بنائیں',
    },
    'woezzutp': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    '2bj20mi4': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'oztjr3ws': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'hc87g50d': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    '8ct6cr3a': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'e368pegn': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'yv65a6i5': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    '4r7kaahz': {
      'en': 'Calling',
      'bn': 'কলিং',
      'hi': 'कॉलिंग',
      'ml': 'വിളിക്കുന്നു',
      'or': 'କଲ୍ କରୁଛି |',
      'ta': 'அழைப்பு',
      'te': 'పిలుస్తోంది',
      'ur': 'کال کرنا',
    },
    '9zk4wopm': {
      'en': 'Not Called',
      'bn': 'ডাকা হয়নি',
      'hi': 'नहीं बुलाया गया',
      'ml': 'വിളിച്ചിട്ടില്ല',
      'or': 'କଲ୍ ହୋଇନାହିଁ |',
      'ta': 'அழைக்கப்படவில்லை',
      'te': 'పిలవలేదు',
      'ur': 'نہیں بلایا',
    },
    'xn2fkope': {
      'en': 'Pending Review',
      'bn': 'মুলতুবি পর্যালোচনা',
      'hi': 'लंबित समीक्षा',
      'ml': 'അവശേഷിക്കുന്ന നിരൂപണം',
      'or': 'ବିଚାରାଧୀନ ସମୀକ୍ଷା',
      'ta': 'மதிப்பாய்வு நிலுவையில் உள்ளது',
      'te': 'పెండింగ్ రివ్యూ',
      'ur': 'زیر التواء جائزہ',
    },
    'jv85czds': {
      'en': 'Closed',
      'bn': 'বন্ধ',
      'hi': 'बंद किया हुआ',
      'ml': 'അടച്ചു',
      'or': 'ବନ୍ଦ |',
      'ta': 'மூடப்பட்டது',
      'te': 'మూసివేయబడింది',
      'ur': 'بند',
    },
    'swt4x372': {
      'en': 'Completed',
      'bn': 'সম্পন্ন',
      'hi': 'पुरा होना।',
      'ml': 'പൂർത്തിയാക്കി',
      'or': 'ସମାପ୍ତ',
      'ta': 'நிறைவு',
      'te': 'పూర్తయింది',
      'ur': 'مکمل',
    },
    '5w6ne1dl': {
      'en': 'Please select...',
      'bn': 'অনুগ্রহ করে নির্বাচন করুন...',
      'hi': 'कृपया चयन कीजिए...',
      'ml': 'ദയവായി തിരഞ്ഞെടുക്കുക...',
      'or': 'ଦୟାକରି ଚୟନ କରନ୍ତୁ ...',
      'ta': 'தயவு செய்து தேர்வு செய்யவும்...',
      'te': 'దయచేసి ఎంచుకోండి...',
      'ur': 'براہ مہربانی منتخب کریں...',
    },
    'uhfmgei0': {
      'en': 'Search for an item...',
      'bn': 'একটি আইটেম খুঁজুন...',
      'hi': 'कोई आइटम खोजें...',
      'ml': 'ഒരു ഇനത്തിനായി തിരയുക...',
      'or': 'ଏକ ଆଇଟମ୍ ପାଇଁ ସନ୍ଧାନ ...',
      'ta': 'ஒரு பொருளைத் தேடு...',
      'te': 'వస్తువు కోసం వెతకండి...',
      'ur': 'ایک آئٹم تلاش کریں...',
    },
    'lted0txl': {
      'en': 'All',
      'bn': 'সব',
      'hi': 'सभी',
      'ml': 'എല്ലാം',
      'or': 'ସମସ୍ତ',
      'ta': 'அனைத்து',
      'te': 'అన్నీ',
      'ur': 'تمام',
    },
    'm6iqz668': {
      'en': 'Pending',
      'bn': 'বিচারাধীন',
      'hi': 'लंबित',
      'ml': 'തീർപ്പാക്കാത്തത്',
      'or': 'ବିଚାରାଧୀନ ଅଛି',
      'ta': 'நிலுவையில் உள்ளது',
      'te': 'పెండింగ్‌లో ఉంది',
      'ur': 'زیر التواء',
    },
    'x2pvxk5r': {
      'en': 'Completed',
      'bn': 'সম্পন্ন',
      'hi': 'पुरा होना।',
      'ml': 'പൂർത്തിയാക്കി',
      'or': 'ସମାପ୍ତ',
      'ta': 'நிறைவு',
      'te': 'పూర్తయింది',
      'ur': 'مکمل',
    },
    'txjoh349': {
      'en': 'Calling',
      'bn': 'কলিং',
      'hi': 'कॉलिंग',
      'ml': 'വിളിക്കുന്നു',
      'or': 'କଲ୍ କରୁଛି |',
      'ta': 'அழைப்பு',
      'te': 'పిలుస్తోంది',
      'ur': 'کال کرنا',
    },
    'qube3xir': {
      'en': 'All',
      'bn': 'সব',
      'hi': 'सभी',
      'ml': 'എല്ലാം',
      'or': 'ସମସ୍ତ',
      'ta': 'அனைத்து',
      'te': 'అన్నీ',
      'ur': 'تمام',
    },
    'mxalfkji': {
      'en': '50%',
      'bn': '৫০%',
      'hi': '50%',
      'ml': '50%',
      'or': '50% |',
      'ta': '50%',
      'te': '50%',
      'ur': '50%',
    },
    'z6o24u9q': {
      'en': 'Notifications',
      'bn': 'বিজ্ঞপ্তি',
      'hi': 'सूचनाएं',
      'ml': 'അറിയിപ്പുകൾ',
      'or': 'ବିଜ୍ଞପ୍ତିଗୁଡିକ',
      'ta': 'அறிவிப்புகள்',
      'te': 'నోటిఫికేషన్‌లు',
      'ur': 'اطلاعات',
    },
    'poegde7v': {
      'en': 'Notifications',
      'bn': 'বিজ্ঞপ্তি',
      'hi': 'सूचनाएं',
      'ml': 'അറിയിപ്പുകൾ',
      'or': 'ବିଜ୍ଞପ୍ତିଗୁଡିକ',
      'ta': 'அறிவிப்புகள்',
      'te': 'నోటిఫికేషన్‌లు',
      'ur': 'اطلاعات',
    },
    'v3vjad01': {
      'en': 'Turn on notifications',
      'bn': 'বিজ্ঞপ্তি চালু করুন',
      'hi': 'सूचनाओं पर मुड़ें',
      'ml': 'അറിയിപ്പുകൾ ഓണാക്കുക',
      'or': 'ବିଜ୍ଞପ୍ତିଗୁଡିକ ଟର୍ନ୍ ଅନ୍ କରନ୍ତୁ |',
      'ta': 'அறிவிப்புகளை இயக்கவும்',
      'te': 'నోటిఫికేషన్‌లను ఆన్ చేయండి',
      'ur': 'اطلاعات کو آن کریں۔',
    },
    'bqjgqich': {
      'en': 'Male',
      'bn': 'পুরুষ',
      'hi': 'नर',
      'ml': 'ആൺ',
      'or': 'ପୁରୁଷ',
      'ta': 'ஆண்',
      'te': 'పురుషుడు',
      'ur': 'مرد',
    },
    'rzl2h9ar': {
      'en': 'Female',
      'bn': 'মহিলা',
      'hi': 'महिला',
      'ml': 'സ്ത്രീ',
      'or': 'ମହିଳା',
      'ta': 'பெண்',
      'te': 'స్త్రీ',
      'ur': 'عورت',
    },
    'qtchqf19': {
      'en': 'Other',
      'bn': 'অন্যান্য',
      'hi': 'अन्य',
      'ml': 'മറ്റുള്ളവ',
      'or': 'ଅନ୍ୟମାନେ |',
      'ta': 'மற்றவை',
      'te': 'ఇతర',
      'ur': 'دیگر',
    },
    '82a75t5n': {
      'en': 'Design',
      'bn': 'ডিজাইন',
      'hi': 'डिज़ाइन',
      'ml': 'ഡിസൈൻ',
      'or': 'ଡିଜାଇନ୍ |',
      'ta': 'வடிவமைப்பு',
      'te': 'రూపకల్పన',
      'ur': 'ڈیزائن',
    },
    'w82xuklg': {
      'en': 'Marketing',
      'bn': 'মার্কেটিং',
      'hi': 'विपणन',
      'ml': 'മാർക്കറ്റിംഗ്',
      'or': 'ମାର୍କେଟିଂ |',
      'ta': 'சந்தைப்படுத்தல்',
      'te': 'మార్కెటింగ్',
      'ur': 'مارکیٹنگ',
    },
    '5uiyxwtk': {
      'en': 'Development',
      'bn': 'উন্নয়ন',
      'hi': 'विकास',
      'ml': 'വികസനം',
      'or': 'ବିକାଶ',
      'ta': 'வளர்ச்சி',
      'te': 'అభివృద్ధి',
      'ur': 'ترقی',
    },
    '3wjkerx7': {
      'en': 'Management',
      'bn': 'ব্যবস্থাপনা',
      'hi': 'प्रबंध',
      'ml': 'മാനേജ്മെന്റ്',
      'or': 'ପରିଚାଳନା',
      'ta': 'மேலாண்மை',
      'te': 'నిర్వహణ',
      'ur': 'انتظام',
    },
    'p6rgfj1v': {
      'en': 'Operations',
      'bn': 'অপারেশন',
      'hi': 'संचालन',
      'ml': 'പ്രവർത്തനങ്ങൾ',
      'or': 'ଅପରେସନ୍ସ',
      'ta': 'செயல்பாடுகள்',
      'te': 'కార్యకలాపాలు',
      'ur': 'آپریشنز',
    },
    'c8uww550': {
      'en': 'Customer Service',
      'bn': 'গ্রাহক সেবা',
      'hi': 'ग्राहक सेवा',
      'ml': 'കസ്റ്റമർ സർവീസ്',
      'or': 'ଗ୍ରାହକ ସେବା',
      'ta': 'வாடிக்கையாளர் சேவை',
      'te': 'వినియోగదారుల సేవ',
      'ur': 'کسٹمر سروس',
    },
    '2rhm2suy': {
      'en': 'Design',
      'bn': 'ডিজাইন',
      'hi': 'डिज़ाइन',
      'ml': 'ഡിസൈൻ',
      'or': 'ଡିଜାଇନ୍ |',
      'ta': 'வடிவமைப்பு',
      'te': 'రూపకల్పన',
      'ur': 'ڈیزائن',
    },
    'e9lb1v9t': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'u1tq2xct': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'il9c28qw': {
      'en': 'Button',
      'bn': 'বোতাম',
      'hi': 'बटन',
      'ml': 'ബട്ടൺ',
      'or': 'ବଟନ୍',
      'ta': 'பொத்தானை',
      'te': 'బటన్',
      'ur': 'بٹن',
    },
    'hxsxj681': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'e7agr7ys': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '65e2tfs2': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ddazihx4': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'db03cpjj': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'fdb9078p': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '80ouzj9q': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '6rzhptp9': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ce8c4ty0': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'hasw6eif': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'xymux6ig': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'iwqu7j0l': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ptf3j0qy': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'kcvqa08x': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dqrzd6sq': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'dpqtohyf': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'v01vf71s': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'gcv6def1': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'um9es99m': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'o4enbz4j': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '8z4tvfh7': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2ybzla8x': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'd1wdf5i1': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'f4rdu9en': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    '2py80kgi': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'p6lsrh2a': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
    'ne8cclp9': {
      'en': '',
      'bn': '',
      'hi': '',
      'ml': '',
      'or': '',
      'ta': '',
      'te': '',
      'ur': '',
    },
  },
].reduce((a, b) => a..addAll(b));
